onfig:
  partial_parse: false
  use_colors: true
  printer_width: 80
  send_anonymous_usage_stats: false

lemonade-testing:
  target: test
  outputs:
    test:
      type: bigquery
      method: oauth
      project:  brilliant-scene-342208
      execution_project:  brilliant-scene-342208
      schema: na
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
